### PR TITLE
[Bug][spark] Fix the bucket join may produce wrong result after bucke…

### LINKED ISSUE #5654: [Bug] The bucket join may not right after bucket rescaled
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.2

### Compute Engine

Spark

### Minimal reproduce step

Currently, Spark bucket join use the table properties bucket number to report the output partition. But, this information can be not right for the partitioned table. 
Because, different partition can have different bucket number, this could lead to the wrong results for the bucket join.

### What doesn't meet your expectations?

.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aitozi**
…t rescaled

### Purpose

Linked issue: close #5654

### CODE REVIEW

File: paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala [hunk 1]
```diff
@@ -62,18 +62,38 @@ case class PaimonScan(
           // so we only support one bucket key case.
           assert(bucketSpec.getNumBuckets > 0)
           assert(bucketSpec.getBucketKeys.size() == 1)
-          val bucketKey = bucketSpec.getBucketKeys.get(0)
-          if (requiredSchema.exists(f => conf.resolver(f.name, bucketKey))) {
-            Some(Expressions.bucket(bucketSpec.getNumBuckets, bucketKey))
-          } else {
-            None
+          extractBucketNumber() match {
```
Comment (JingsongLi) [inline paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala:65]: Add some comments to explain this extraction.

File: paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala [hunk 2]
```diff
@@ -62,18 +62,38 @@ case class PaimonScan(
...
+            case _ => None
           }
         }
 
       case _ => None
     }
   }
 
+  private def extractBucketNumber(): Option[Int] = {
+    val splits = getOriginSplits
```
[the remark this answers is not in the document]
Comment (Aitozi) [reply paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala:83]: the lazyInputPartitions depends on the `bucket` info, so if we use the `lazyInputPartitions`, we will meet StackOverflow here.

File: paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala (hunk 1 above)
Comment (Aitozi) [reply paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala:65]: fixed
