### PR TITLE
[flink] Fix stability of Flink 2.0 test workflow

### LINKED ISSUE #5876: [Bug] Fix stability of Flink 2.0 test workflow
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

a6d2e8376cfb93accfbb2112048edefeb48bc77e

### Compute Engine

Flink

### Minimal reproduce step

Execute the workflow script removed in https://github.com/apache/paimon/commit/a6d2e8376cfb93accfbb2112048edefeb48bc77e.

### What doesn't meet your expectations?

There are unstable build and test problems that affects the stability of this Github Action. These problems should be fixed, and this Action should be enabled again to keep preserving the correctness of the latest Paimon code under Flink 2.0.

### Anything else?

I counted the most recent 100 Action executions before the script is removed, and the problems that caused the failures are as follows.

1. (79%) The Action run successfully.
2. (11%) paimon-e2e-tests relies on paimon-flink-cdc, which is not compiled with `-Pflink2`. The Action failed with a timeout exception when trying to download the latest snapshot of this module.
3. (7%) CatalogTableITCase#testConsumersTable failed. It is a flaky test with race condition.
4. (3%) Various failures that appeared only once.

So we need to fix the problems mentioned in 2 and 3 before enabling the Action again.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by yunfengzhou-hub**
### Purpose

Linked issue: close #5876

This PR fixes the problems that affect the stability of Flink 2.0 test workflow and add back the workflow script again, which was once removed in https://github.com/apache/paimon/commit/a6d2e8376cfb93accfbb2112048edefeb48bc77e.

I counted the most recent 100 Action executions before the script is removed, and the problems that caused the failures are as follows.

1. (79%) The Action run successfully.
2. (11%) paimon-flink-cdc module download timeout.
4. (7%) CatalogTableITCase#testConsumersTable failed. It is a flaky test with race condition.
5. (3%) Various failures that appeared only once.

So we need to fix the problems mentioned in 2 and 3 before enabling the Action again. The fixing is as follows.

#### 2. Build paimon-flink-cdc under Flink 2.0

Example failure Action log: https://github.com/apache/paimon/actions/runs/15804130573/job/44546474506

The failure was because that `paimon-e2e-tests` and `paimon-docs` relies on `paimon-flink-cdc` module, but this module is not compiled when profile `flink2` is enabled. In the attempt to download the snapshot of this module, network connection timeout might occur.

This PR fixes the failure by enabling the compilation of `paimon-flink-cdc` and its pre-module (`paimon-flink1-common`) under `-Pflink2`. This change is supposed not to affect the production code and the releasing process.

#### 3. Fix race condition in CatalogTableITCase#testConsumersTable

Example failure Action log: https://github.com/apache/paimon/actions/runs/15822438299/job/44594579766

This failure was because that the Flink job with the consumer source might not have completed its initialization before the second batch of data is written to the Paimon table. In order to fix it, a blocking operation is added to force the test case to wait for the source's initialization before the next write.

### CODE REVIEW

File: paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java [hunk 1]
```diff
@@ -951,10 +952,13 @@ public void testConsumersTable() throws Exception {
...
-                                "SELECT * FROM T /*+ OPTIONS('consumer-id'='my1','consumer.expiration-time'='3h') */"));
+        CloseableIterator<Row> closeableIterator =
+                streamSqlIter(
+                        "SELECT * FROM T /*+ OPTIONS('consumer-id'='my1','consumer.expiration-time'='3h') */");
+        BlockingIterator<Row, Row> iterator = BlockingIterator.of(closeableIterator);
+
+        // Blocks the main thread until the consumer job is ready.
+        assertThat(closeableIterator).hasNext();
 
         batchSql("INSERT INTO T VALUES (5, 6), (7, 8)");
```
Comment (Sxnan) [inline paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java:960]: Can we just put this line after the assertion?

**Review by Sxnan — COMMENTED** [review]
Thanks for the PR! Just left one minor comment

**Comment by JingsongLi** [comment]
+1
