### PR TITLE
[core] Fix race condition for earliest snapshot

### LINKED ISSUE #3479: [Bug]  streaming read  by  `from-timestamp`   may be occur exception（snapshot file not fund）  sometimes
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

Flink

## Analyze source code in  `SnapshotManager.class` 

when read  earliest snapshot file at step2， the snapshot maybe expired and deleted

### What doesn't meet your expectations?

query job will failed by throw FileNotFoundException

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by yunfengzhou-hub**
### Purpose

Linked issue: close #3479

This PR fixes a racing bug about earliest snapshot. When thread A is trying to get the earliest snapshot of a table, while the snapshot is being expired by thread B, thread A might throw exception that it cannot get the snapshot information from the earliest snapshot id.

This PR fixes the bug by adding retrying logic to seek the second earliest snapshot if the first one cannot be found.

Note that, theoretically speaking, any snapshot (including the latest one) could encounter this issue, but the probability is quite small, so this PR only fixes the bug for invocations on the earliest snapshot.

### Tests

Tests in SnapshotManagerTest are used to verify against the changes.

### API and Format

This change does not affect API or storage format.

### Documentation

This change does not introduce a new feature.

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 1]
```diff
@@ -268,25 +301,43 @@ private Snapshot changelogOrSnapshot(long snapshotId) {
...
      * returned if all snapshots are equal to or later than the timestamp mills.
      */
     public @Nullable Long earlierThanTimeMills(long timestampMills, boolean startFromChangelog) {
-        Long earliestSnapshot = earliestSnapshotId();
+        Long earliestSnapshotId = earliestSnapshotId();
         Long earliest;
         if (startFromChangelog) {
             Long earliestChangelog = earliestLongLivedChangelogId();
-            earliest = earliestChangelog == null ? earliestSnapshot : earliestChangelog;
+            earliest = earliestChangelog == null ? earliestSnapshotId : earliestChangelog;
```
Comment (wwj6591812) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:321]: earliestChangelogId

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 2]
```diff
@@ -209,7 +226,23 @@ public boolean longLivedChangelogExists(long snapshotId) {
 
     public @Nullable Snapshot earliestSnapshot() {
         Long snapshotId = earliestSnapshotId();
-        return snapshotId == null ? null : snapshot(snapshotId);
+        if (snapshotId == null) {
+            return null;
+        }
+
+        Long latest = null;
```
Comment (wwj6591812) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:233]: latestSnapshotId

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 3]
```diff
@@ -268,25 +301,43 @@ private Snapshot changelogOrSnapshot(long snapshotId) {
...
             return null;
         }
 
-        if (changelogOrSnapshot(earliest).timeMillis() >= timestampMills) {
+        Snapshot earliestSnapshot = null;
+        while (earliest <= latest) {
+            try {
+                earliestSnapshot = tryGetChangelogOrSnapshot(earliest);
+                break;
+            } catch (FileNotFoundException e) {
```
Comment (wwj6591812) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:335]: Add a log here?

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 4]
```diff
@@ -209,7 +226,23 @@ public boolean longLivedChangelogExists(long snapshotId) {
...
-        return snapshotId == null ? null : snapshot(snapshotId);
+        if (snapshotId == null) {
+            return null;
+        }
+
+        Long latest = null;
+        do {
+            try {
+                return tryGetSnapshot(snapshotId);
+            } catch (FileNotFoundException e) {
```
Comment (wwj6591812) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:237]: Add a log here?

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 5]
```diff
@@ -163,11 +163,28 @@ public Snapshot tryGetSnapshot(long snapshotId) throws FileNotFoundException {
         return snapshot;
     }
 
+    private @Nullable Snapshot tryGetEarliestSnapshotLaterThanOrEqualTo(
+            long snapshotId, long stopId) {
```
Comment (wwj6591812) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:167]: stopSnapshotId?

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 6]
```diff
@@ -434,9 +487,17 @@ private Snapshot changelogOrSnapshot(long snapshotId) {
...
+
+        if (earliestSnapShot == null) {
+            return null;
+        }
+
         Long earliestWatermark = null;
         // find the first snapshot with watermark
-        if ((earliestWatermark = snapshot(earliest).watermark()) == null) {
+        if ((earliestWatermark = earliestSnapShot.watermark()) == null) {
             while (earliest < latest) {
```
Comment (JingsongLi) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:501]: I think there are some risks. Earliest should be re-assigned.

Maybe you should just optimize `earliestSnapshot`. And use this method in many places.

Comment (yunfengzhou-hub) [reply paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java]: Given that some earliestSnapshot methods use binary search while others use linear, I extracted and optimized two kinds of paths. Please take a look.
