### PR TITLE
[core] Resolve hms Permission.NotAllow error

### LINKED ISSUE #5485: [Feature] identify the "Permission.NotAllow" error returned by HMS.
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

When calling the getTable interface of HMS, if the server-side validation finds that the user does not have permission and returns an exception, Paimon directly throws a RuntimeException with the message 'Cannot determine if table ' + identifier.getFullName() + ' is a Paimon table.' This makes it difficult to intuitively obtain the actual exception information.

### Solution

When identifying the exception information that contains "Permission.NotAllow", throw TableNoPermissionException

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by gavin9402**
### Purpose

Linked issue: close #5485

Identify the "Permission.NotAllow" error returned by HMS

### Tests

N/A

### API and Format

N/A

### Documentation

N/A

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java [hunk 1]
```diff
@@ -789,12 +789,12 @@ public Identifier identifier() {
     /** Exception for trying to operate on the table that doesn't have permission. */
     class TableNoPermissionException extends RuntimeException {
 
-        private static final String MSG = "Table %s has no permission.";
+        private static final String MSG = "Table %s has no permission: %s.";
```
Comment (JingsongLi) [inline paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java:792]: Can you revert this modification? the root cause already contain the message.

Comment (gavin9402) [reply paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java]: done

**Comment by JingsongLi** [comment]
+1
