### PR TITLE
[core] Log a warning for invalid partition values instead of throwing an exception when enable partition mark done. 

### LINKED ISSUE #5976: [Bug] Log a warning for invalid partition values instead of throwing an exception when enable partition mark done.
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0

### Compute Engine

flink 1.18

### Minimal reproduce step

1.enable partition mark done;
2.write into `__DEFAULT_PARTITION__` 
3.when mark done `__DEFAULT_PARTITION__` , exception happens and job would fail over:

Image

### What doesn't meet your expectations?

It is more reasonable to log a warning rather than throwing an exception directly, similar to how partition expiration is handled. This approach prevents the job from getting stuck in a continuous failover loop when encountering invalid partition values.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhoulii**
### Purpose

Linked issue: close #5976

### CODE REVIEW

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTrigger.java [hunk 1]
```diff
@@ -167,7 +176,10 @@ LocalDateTime extractDateTime(String partition) {
         try {
             return timeExtractor.extract(extractPartitionSpecFromPath(new Path(partition)));
         } catch (DateTimeParseException e) {
-            throw new RuntimeException("Can't extract datetime from partition " + partition, e);
+            LOG.warn(
+                    "Can't extract datetime from partition {}, please check configuration items 'partition.timestamp-formatter' and 'partition.timestamp-pattern'.",
+                    partition);
+            return LocalDateTime.MIN;
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTrigger.java]: Can we just return Optional.empty?

**Comment by JingsongLi** [comment]
+1
