### PR TITLE
[Bug] when object table metadata not null refresh table throw error

### LINKED ISSUE #5584: [Bug] when object table metadata not null throw exception
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

paimon master branch, commit id: 3501fe405035c91251624d4d8d0a9a1207abf190

### Compute Engine

flink 1.17

### Minimal reproduce step

Execution statement throws exception, rootCauseMessage = FlinkSQLException: org.apache.flink.table.api.TableException: Fail to call the procedure. The reason is java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.paimon.data.BinaryString.
	at org.apache.flink.table.planner.operations.PlannerCallProcedureOperation.invokeCallMethod(PlannerCallProcedureOperation.java:234)
	at org.apache.flink.table.planner.operations.PlannerCallProcedureOperation.callProcedure(PlannerCallProcedureOperation.java:195)
	at org.apache.flink.table.planner.operations.PlannerCallProcedureOperation.execute(PlannerCallProcedureOperation.java:117)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1720)
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.callOperation(OperationExecutor.java:613)
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.executeOperation(OperationExecutor.java:454)
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.lambda$executeStatement$1(OperationExecutor.java:228)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
	at org.apache.flink.table.gateway.service.context.SqlGatewaySecurityContext.runSecured(SqlGatewaySecurityContext.java:77)
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.executeStatement(OperationExecutor.java:208)
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.executeStatement(OperationExecutor.java:194)
	at org.apache.flink.table.gateway.service.SqlGatewayServiceImpl.lambda$executeStatement$1(SqlGatewayServiceImpl.java:253)
	at org.apache.flink.table.gateway.service.operation.OperationManager.lambda$submitOperation$1(OperationManager.java:133)
	at org.apache.flink.table.gateway.service.operation.OperationManager$Operation.lambda$run$0(OperationManager.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.table.planner.operations.PlannerCallProcedureOperation.invokeCallMethod(PlannerCallProcedureOperation.java:225)
	... 22 more
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.paimon.data.BinaryString
	at org.apache.paimon.table.object.ObjectTable$ObjectTableImpl.refresh(ObjectTable.java:189)
	at org.apache.paimon.flink.procedure.RefreshObjectTableProcedure.call(RefreshObjectTableProcedure.java:46)
	... 27 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.paimon.data.BinaryString
	at org.apache.paimon.data.GenericArray.getString(GenericArray.java:215)
	at org.apache.paimon.arrow.writer.ArrowFieldWriters$StringWriter.doWrite(ArrowFieldWriters.java:97)
	at org.apache.paimon.arrow.writer.ArrowFieldWriter.write(ArrowFieldWriter.java:82)
	at org.apache.paimon.arrow.writer.ArrowFieldWriters$MapWriter.doWrite(ArrowFieldWriters.java:671)
	at org.apache.paimon.arrow.writer.ArrowFieldWriter.write(ArrowFieldWriter.java:82)
	at org.apache.paimon.arrow.vector.ArrowFormatWriter.write(ArrowFormatWriter.java:80)
	at org.apache.paimon.arrow.vector.ArrowFormatCWriter.write(ArrowFormatCWriter.java:57)
	at org.apache.paimon.format.common.writer.ArrowBundleWriter.addElement(ArrowBundleWriter.java:63)
	at org.apache.paimon.io.SingleFileWriter.writeImpl(SingleFileWriter.java:127)
	at org.apache.paimon.io.StatsCollectingSingleFileWriter.write(StatsCollectingSingleFileWriter.java:61)
	at org.apache.paimon.io.RowDataFileWriter.write(RowDataFileWriter.java:79)
	at org.apache.paimon.io.RowDataFileWriter.write(RowDataFileWriter.java:45)
	at org.apache.paimon.io.RollingFileWriter.write(RollingFileWriter.java:80)
	at org.apache.paimon.append.AppendOnlyWriter$DirectSinkWriter.write(AppendOnlyWriter.java:404)
	at org.apache.paimon.append.AppendOnlyWriter.write(AppendOnlyWriter.java:161)
	at org.apache.paimon.append.AppendOnlyWriter.write(AppendOnlyWriter.java:66)
	at org.apache.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:161)
	at org.apache.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:175)
	at org.apache.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:147)
	at org.apache.paimon.table.object.ObjectRefresh.refresh(ObjectRefresh.java:52)
	at org.apache.paimon.table.object.ObjectTable$ObjectTableImpl.refresh(ObjectTable.java:187)
	... 28 more

### What doesn't meet your expectations?

The program should not throw exception

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by kaixuanzhang123**
### Purpose
bug fix : object table metadata not null throw error

Linked issue: close #5584
https://github.com/apache/paimon/issues/5584

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/table/object/ObjectRefresh.java [hunk 1]
```diff
@@ -75,7 +78,23 @@ private static InternalRow toRow(FileStatus file) {
                 Optional.ofNullable(file.getMetadataModificationTime())
                         .map(Timestamp::fromEpochMillis)
                         .orElse(null),
-                Optional.ofNullable(file.getMetadata()).map(GenericMap::new).orElse(null));
+                metadata);
+    }
+
+    /** 将普通 Map<String, String> 类型的 metadata 转换为 Paimon 内部支持的 GenericMap 结构。 */
```
Comment (yuzelin) [inline paimon-core/src/main/java/org/apache/paimon/table/object/ObjectRefresh.java:84]: Please use english for comment.

**Comment by yuzelin** [comment]
Try to run `mvn spotless::apply` to fix checkstyle error.

**Comment by JingsongLi** [comment]
+1
