### PR TITLE
[flink] fix that AppendBypassCoordinateOperator does not generate compaction tasks.

### LINKED ISSUE #5896: [Bug] AppendBypassCoordinateOperator does not generate compaction tasks.
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0

### Compute Engine

flink 1.18

### Minimal reproduce step

Once an exception occurs in method `AppendBypassCoordinateOperator#asyncPlan`, it will not be scheduled for execution again.

### What doesn't meet your expectations?

The Flink job should fail in this scenario. Otherwise, the issue will go unnoticed by users, preventing small files from being compacted and ultimately resulting in an excessive number of small files on the storage system.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhoulii**
### Purpose

Linked issue: close #5896

### CODE REVIEW

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java [hunk 1]
```diff
@@ -85,10 +87,15 @@ public void open() throws Exception {
...
-                break;
+            try {
+                List<AppendCompactTask> tasks = coordinator.run();
+                compactTasks.addAll(tasks);
+                if (tasks.isEmpty()) {
+                    break;
+                }
+            } catch (Throwable t) {
+                LOG.error("Fatal exception happened when generating compaction tasks.", t);
+                this.throwable = t;
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java:98]: We should return here?

Comment (zhoulii) [reply paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java:98]: > We should return here?

fixed.

**Review by JingsongLi — APPROVED** [review]
+1
