### PR TITLE
[Flink]fix nested row type convert to serializer loop

### LINKED ISSUE #3460: [Bug] Serializers were created infinitely and caused OOM for 0.8
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

Flink 1.18.1

### Minimal reproduce step

Serializers were created infinitely for the following recursive schema after bumping up Paimon to 0.8.
```
ARRAY <
    ROW <
        `null_value` STRING,
        `number_value` DOUBLE,
        `string_value` STRING,
        `bool_value` BOOLEAN,
        `struct_value` ROW <
            `fields` ARRAY <
                ROW <
                    `key` STRING,
                    `value` ROW <
                        `null_value` STRING,
                        `number_value` DOUBLE,
                        `string_value` STRING,
                        `bool_value` BOOLEAN,
                        `struct_value` ROW <
                            `fields` ARRAY <
                                ROW <
                                    `key` STRING,
                                    `value` ROW <
                                        `null_value` STRING,
                                        `number_value` DOUBLE,
                                        `string_value` STRING,
                                        `bool_value` BOOLEAN
                                    >
                                > NOT NULL
                            >
                        >,
                        `list_value` ROW <
                            `values` ARRAY <
                                ROW <
                                    `null_value` STRING,
                                    `number_value` DOUBLE,
                                    `string_value` STRING,
                                    `bool_value` BOOLEAN
                                > NOT NULL
                            >
                        >
                    >
                > NOT NULL
            >
        >,
        `list_value` ROW <
            `values` ARRAY <
                ROW <
                    `null_value` STRING,
                    `number_value` DOUBLE,
                    `string_value` STRING,
                    `bool_value` BOOLEAN,
                    `struct_value` ROW <
                        `fields` ARRAY <
                            ROW <
                                `key` STRING,
                                `value` ROW <
                                    `null_value` STRING,
                                    `number_value` DOUBLE,
                                    `string_value` STRING,
                                    `bool_value` BOOLEAN
                                >
                            > NOT NULL
                        >
                    >,
                    `list_value` ROW <
                        `values` ARRAY <
                            ROW <
                                `null_value` STRING,
                                `number_value` DOUBLE,
                                `string_value` STRING,
                                `bool_value` BOOLEAN
                            > NOT NULL
                        >
                    >
                > NOT NULL
            >
        >
    > NOT NULL
>
```

### What doesn't meet your expectations?

The test case worked well with Paimon 0.7 but caused OOM with Paimon 0.8.
image

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by wg1026688210**
### Purpose

Linked issue: close #3460

### CODE REVIEW

File: paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalRowSerializer.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ public InternalRowSerializer(DataType[] types, Serializer<?>[] fieldSerializers)
         for (int i = 0; i < types.length; i++) {
             DataType type = types[i];
             fieldGetters[i] = InternalRow.createFieldGetter(type, i);
-            valueSetters[i] = BinaryWriter.createValueSetter(type);
+            valueSetters[i] = BinaryWriter.createValueSetter(type, this);
```
Comment (JingsongLi) [inline paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalRowSerializer.java:76]: it should be `fieldSerializers`?

**Review by JingsongLi — APPROVED** [review]
+1
