### PR TITLE
[flink] Fix performance issue in CdcActionCommonUtils

### LINKED ISSUE #3549: [Bug][cdc] performance issue in CdcActionCommonUtils
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

Flink

### Minimal reproduce step

none

### What doesn't meet your expectations?

image
When checking for duplicate fields, unnecessary errMsg string concatenation is performed each time, which may cause performance problems when the data volume is large and there are many fields.
image

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by MOBIN-F**
### Purpose

Linked issue: close #3549

### CODE REVIEW

**Review by JingsongLi — APPROVED** [review]
+1

File: paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java [hunk 1]
```diff
@@ -112,9 +112,9 @@ public static List<DataField> fieldNameCaseConvert(
                                 return field;
                             }
                             String columnLowerCase = field.name().toLowerCase();
-                            checkArgument(
-                                    existedFields.add(columnLowerCase),
-                                    columnDuplicateErrMsg.apply(field.name()));
+                            if (!existedFields.add(columnLowerCase)) {
+                                columnDuplicateErrMsg.apply(field.name());
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java:116]: throw exception?

Comment (MOBIN-F) [reply paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java]: done.
