### PR TITLE
[bug][spark] fix ambiguous __paimon_file_path when merging from paimo…

### LINKED ISSUE #5024: [Bug] Merge into paimon table from another paimon table will have ambiguous __paimon_file_path
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0

### Compute Engine

Spark

### Minimal reproduce step

```scala
  test(s"Paimon MergeInto: two paimon table") {
    withTable("source", "target") {
      createTable("target", "a INT, b INT, c STRING", Seq("a"))
      createTable("source", "a INT, b INT, c STRING", Seq("a"))

      spark.sql("INSERT INTO source values (1, 100, 'c11'), (3, 300, 'c33')")
      spark.sql("INSERT INTO target values (1, 10, 'c1'), (2, 20, 'c2')")

      spark.sql(s"""
                   |MERGE INTO target
                   |USING source
                   |ON target.a = source.a
                   |WHEN MATCHED THEN
                   |UPDATE SET a = source.a, b = source.b, c = source.c
                   |""".stripMargin)

      checkAnswer(
        spark.sql("SELECT * FROM target ORDER BY a, b"),
        Row(1, 100, "c11") :: Row(2, 20, "c2") :: Nil)
    }
```

### What doesn't meet your expectations?

Image

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aitozi**
…n table

### Purpose

Linked issue: close #5024

### CODE REVIEW

File: paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala [hunk 1]
```diff
@@ -48,6 +48,28 @@ abstract class MergeIntoTableTestBase extends PaimonSparkTestBase with PaimonTab
     }
   }
 
+  test(s"Paimon MergeInto: two paimon table") {
```
Comment (YannByron) [inline paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala:51]: Sorry. I can't understand the effect of this PR by this test.

Comment (Aitozi) [reply paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala:51]: This would merge from one paimon table to another, which will have two paimon source join and can cover the ambiguous __paimon_file_path case

**Comment by Aitozi** [comment]
@YannByron please help take a look again

File: paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala (hunk 1 above)
Comment (Zouxxyy) [reply paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala:51]: @Aitozi I put this case into the latest master branch, and it seems to execute successfully, can you check it again

Comment (Aitozi) [reply paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala:51]: It still fails 
image

**Comment by LinMingQiang** [comment]
My environment can reproduce this problem.

```Paimon MergeInto: two paimon table


Reference '__paimon_file_path' is ambiguous, could be: paimon.test.target.__paimon_file_path, paimon.test.source.__paimon_file_path.; line 2 pos 0
org.apache.spark.sql.AnalysisException: Reference '__paimon_file_path' is ambiguous, could be: paimon.test.target.__paimon_file_path, paimon.test.source.__paimon_file_path.; line 2 pos 0
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.resolve(package.scala:386)```

File: paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala (hunk 1 above)
Comment (Zouxxyy) [reply paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala:51]: My mistake, append table will fail

**Review by Zouxxyy — APPROVED** [review]
+1, thanks!
