### PR TITLE
[core] close files in CompactRewriter to avoid file leaks.

### LINKED ISSUE #3408: [Bug] File leaks may occur with CompactRewriter.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

paimon-0.8

### Compute Engine

flink 1.17

### Minimal reproduce step

In https://github.com/apache/paimon/blob/master/paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java#L156, `iterator` / `compactFileWriter` / `changelogFileWriter` may throw an `Exception`, which will cause the file to fail to be closed and cleaned.

### What doesn't meet your expectations?

We should close `iterator` / `compactFileWriter` / `changelogFileWriter` and clean the file when an exception occurs.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liming30**
[core] close files in `CompactRewriter` to avoid file leaks.
### Purpose

Linked issue: close #3408 

### Tests

- org.apache.paimon.mergetree.ChangelogMergeTreeRewriterTest#testRewriteFailAndCleanupFiles
- org.apache.paimon.mergetree.ChangelogMergeTreeRewriterTest#testRewriteSuccess

### API and Format

No
### Documentation

No

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java [hunk 1]
```diff
@@ -151,18 +154,22 @@ private CompactResult rewriteOrProduceChangelog(
...
-            if (iterator != null) {
-                iterator.close();
-            }
-            if (compactFileWriter != null) {
-                compactFileWriter.close();
-            }
-            if (changelogFileWriter != null) {
-                changelogFileWriter.close();
+            try {
+                IOUtils.closeAll(iterator, compactFileWriter, changelogFileWriter);
```
Comment (JingsongLi) [inline paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java:161]: I do a test:
```
    public static void main(String[] args) throws Exception {
        Exception exception = null;
        try {
            boolean b = ThreadLocalRandom.current().nextBoolean();
            if (b) {
                throw new RuntimeException();
            }
        } catch (Exception e) {
            exception = e;
        } finally {
            System.out.println(exception == null);
            if (exception != null) {
                throw exception;
            }
        }
    }
```

The exception is visible in `finally`.

**Review by JingsongLi — APPROVED** [review]
+1
